version: "3.8"

services:
    front:
        container_name: front
        restart: on-failure
        build:
            context: .
            dockerfile: ./compose/react/Dockerfile
        command: >
            sh -c "npm install && npm start"
        stdin_open: true
        env_file:
            - ./.envs/.env
        ports:
            - "3000:3000"
        volumes:
            - .:/code:cached
